# Generated by Django 4.1.4 on 2023-01-14 19:42
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newpoll', '0008_question_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
