# Generated by Django 4.1.4 on 2023-01-14 14:53
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newpoll', '0006_choice_delete_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
