# Generated by Django 4.1.4 on 2023-01-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newpoll', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vote',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
